# Default rubocop confiugration for Chillbud

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Max: 30

Metrics/ClassLength:
  Max: 1500

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
